### ISSUE TITLE
SpotifyLoginが完了したときに戻すURLがわからない

### ISSUE THREAD

**Issue by onsd** [kanko-dori/favox#101]
## WHY

ログインフローにて、SpotifyLoginが完了した後は `cloud function` からの 301 でredirect をしている。
このとき、`/index` のようなリダイレクトの仕方をすると *`cloud function` のエンドポイントにリダイレクトされる* ため、クライアントのページに戻れなくなる

## WHAT

1. 毎回リダイレクト先を書き換える
2. `origin_url` みたいなヘッダーを用意し、それを用いてクライアントのページにリダイレクトできるようにする

**Comment by ssssota** [comment]
これ解決？

**Comment by onsd** [comment]
見た感じ解決してそう
