### ISSUE TITLE
プレイリストが5つしか表示されない

### ISSUE THREAD

**Issue by onsd** [kanko-dori/favox#121]
## WHY

`/my` をみると、自分のプレイリストの古いやつから5つだけ表示されているように見える

![image](https://user-images.githubusercontent.com/29172177/101975515-85035280-3c80-11eb-8934-458e55143ea8.png)

## WHAT

- 古い順・新しい順はどうするか
- 表示させる数は何個がいいか
- 検索できるようにするか

などを話し合ったほうが良い気がする

**Comment by onsd** [comment]
個人的には
- 新しい順
- 可能な限り多く出す
でとりあえずよいかなと思っている

**Comment by ssssota** [comment]
ロジック的には全部表示されるようにしてるつもりなんだが、手元のプレイリストが１つしか無いので動作確認不足でしかない

**Comment by ssssota** [comment]
API上は20個一度にとってこれる仕様なのでなにかおかしい

**Comment by onsd** [comment]
> API上は20個一度にとってこれる仕様なのでなにかおかしい

なるほど
僕もちょっとみてみます

**Comment by onsd** [comment]
1. APIは新しいプレイリストから20個ずつ返してる
1. state に 20個保存する
1. next があるとき次の20個を取りに行く
1. state に保存する
...

上記のようなループで、毎回 stateに新しいプレイリストが保存されている
古い6個がでてるのは、僕が46 個プレイリストがあって 20, 20, 6 で表示されているからっぽい

**Comment by ssssota** [comment]
後で直す

**Comment by onsd** [comment]
https://github.com/kanko-dori/favox/blob/d3851ec9144656cd7f16185fc3c8c65905501879/src/frontend/lib/spotify.ts#L72-L80

ここの`playlists` に値が無いっぽい

**Comment by ssssota** [comment]
原因と直し方は頭の中にあるので大丈夫です
