### ISSUE TITLE
dominantColor を optional にしたい

### ISSUE THREAD

**Issue by onsd** [kanko-dori/favox#126]
## WHY

https://github.com/kanko-dori/favox/blob/0538ee780903c34e6cb3fd5f2201edb0c5c93ce9/src/types.ts#L132-L137

dominantColorの生成に失敗したときに落ちそう

## WHAT

なかったときには何色を出すか考えたい

**Comment by ssssota** [comment]
これ、フロントでとりあえず白(#ffffff)になってる
