### ISSUE TITLE
画像を元に dominant color を作成する関数をつくる

### ISSUE THREAD

**Issue by onsd** [kanko-dori/favox#53]
## WHY
ジャケットの画像から背景色を作成したい

![image](https://user-images.githubusercontent.com/29172177/97795910-3f01aa80-1c4f-11eb-9b37-3dfb170622e0.png)

## WHAT
dominant color を作成する関数をつくる
画像を渡したらdominant color を返す関数でよさそう

## 使い方
Songs の onCreate で呼べばいいかなと思っている

**Comment by ssssota** [comment]
https://lokeshdhakar.com/projects/color-thief/ のUsing in Node節を参考に。
