### ISSUE TITLE
Spotify API tokenが１時間でExpireする

### ISSUE THREAD

**Issue by ssssota** [kanko-dori/favox#64]
## WHY

Spotify API tokenが１時間で失効する

## WHAT

FirestoreにTOKENを１時間？毎に取得するクロンFunctionを作成する。

- TOKENを取得する関数
- TOKENを保存する関数

**Comment by ssssota** [comment]
TOKEN取得はcronなFunctionで実現可能
https://firebase.google.com/docs/functions/schedule-functions?hl=ja

**Comment by onsd** [comment]
API Token はユーザがOAuthで取得するのでこの issue は close

ref. #71
