### ISSUE TITLE
Spotify APIの取り扱い

### ISSUE THREAD

**Issue by onsd** [kanko-dori/favox#71]
## WHY

Token の取得方法・取り扱い方が決まっていない

## WHAT

1. front で firebase anonymous login を行う
2. front で spotify ログインを行う
3. `1.` で取得したuuid をkey にして spotify api token を保存する
4. プレイリストの作成・更新は `3.` で保存した token を用いて行う
	- 実行者の検証は firestore の uuid を用いて行う

**Comment by ssssota** [comment]
これも解決？
Exipredとかもう少し考慮するべきみたいなのはあるか

**Comment by onsd** [comment]
ログインした後2時間後くらいにログインしたときに、refresh しないといけないとかはあるかも
別issue にするか

**Comment by ssssota** [comment]
OK
閉じます
