### ISSUE TITLE
Firestore <-> クライアントのデータの受け渡し

### ISSUE THREAD

**Issue by onsd** [kanko-dori/favox#81]
## WHY

ref. https://github.com/kanko-dori/favox/issues/48

> 楽曲の基本情報はSpotifyAPIから取得する？ドミナントカラーはFirestoreから取得する？
Firestoreから取得するなら、APIを用意して適当に成形して送る？フロントから直接叩く？
など、選択の幅があるものを決定する必要がある。

## WHAT

- [ ] 楽曲の基本情報
- [ ] ドミナントカラーをどう取得するか
	- [ ] firestore から取得する場合, cloud functions を用意する or フロントから直接叩く

**Comment by ssssota** [comment]
設計書HackMDにて解決
